# Buildpack API version
api = "0.10"

# Buildpack ID and metadata
[buildpack]
id = "spring-boot/spring-boot-test-info"
version = "0.0.4"
name = "Spring Boot Test Info Buildpack"
homepage = "https://github.com/spring-projects/spring-boot"

# Targets that the buildpack will work with
[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
