# Buildpacks to include in builder
[[buildpacks]]
id = "spring-boot/spring-boot-test-info"
version = "0.0.1"
uri = "../buildpacks/test-info"

# Order used for detection
[[order]]
[[order.group]]
id = "spring-boot/spring-boot-test-info"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "paketobuildpacks/build-jammy-tiny"
[run]
[[run.images]]
image = "paketobuildpacks/run-jammy-tiny"

# Stack that will be used by the builder (deprecated)
[stack]
id = "io.buildpacks.stacks.jammy.tiny"
build-image = "paketobuildpacks/build-jammy-tiny"
run-image = "paketobuildpacks/run-jammy-tiny"

# Lifecycle executable version that will be used by the builder
[lifecycle]
version = "0.19.5"